// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const envSupabaseUrl = String(import.meta.env.VITE_SUPABASE_URL ?? "").trim();
const envSupabaseAnonKey = String(import.meta.env.VITE_SUPABASE_ANON_KEY ?? "").trim();

if (!envSupabaseUrl || !envSupabaseAnonKey) {
  throw new Error(
    "Supabase nao configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY no arquivo .env.",
  );
}

export const SUPABASE_URL = envSupabaseUrl;
export const SUPABASE_PUBLISHABLE_KEY = envSupabaseAnonKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);



